`ifndef CPU_VH
`define CPU_VH 
`include "config.vh"
`include "pc.v"
`include "pc_alu.v"
`include "inst_mem.v"
`include "reg_if_id.v"
`include "reg_file.v"
`include "cu.v"
`include "id_tmp_reg.v"
`include "main_alu_control.v"
`include "reg_id_ex.v"
`include "main_alu.v"
`include "ex_tmp_reg.v"
`include "reg_ex_mem.v"
`include "data_mem.v"
`include "mem_tmp_reg.v"
`include "reg_mem_wb.v"
`endif
